parameters:
    simple_event_store_manager.class: SimpleEventStoreManager\Bundle\Service\EventStoreManager

services:
    simple_event_store_manager:
        class: "%simple_event_store_manager.class%"
        arguments:
            - "%simple_event_store_manager%"
